feat(favicon): Add a magnificent favicon
24chevres/24chevres.com pull request #16
Opened 2017-10-24 20:30 UTC by deuzu

2017-10-25 07:49 UTC, frenchfal commented
Ceci est la beauté

2017-10-25 08:16 UTC, izeau requested changes

2017-10-25 08:16 UTC, izeau commented on package.json
> +  "dependencies": {
`devDependencies`

2017-10-25 08:16 UTC, izeau commented on package.json
> +    "http-server": "^0.10.0"
Remplace par `live-server`

2017-10-25 08:16 UTC, izeau commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
_LAME_

2017-10-25 13:40 UTC, NassK commented
fdp <3

2017-10-26 16:22 UTC, merged

2017-10-27 09:45 UTC, deuzu commented
@NassK Democracy has been enforced. Resistance is futile.