Make goat great again
24chevres/24chevres.com pull request #22
Opened 2018-02-14 16:56 UTC by hanfi

le don de soi

2018-02-14 17:00 UTC, deuzu requested changes

2018-02-14 17:00 UTC, deuzu commented on assets/default.css
> +}
No newline at the end of the file

2018-02-14 17:00 UTC, deuzu commented on index.html
> +        <a class="donate" href="http://association-chevre-savoie.fr/don-association/">
No https? =(

2018-02-14 17:15 UTC, hanfi commented on assets/default.css
> +}
pardon fixed

2018-02-14 20:53 UTC, deuzu approved these changes

2018-02-15 15:24 UTC, patpetit commented on assets/default.css
> +}
T'aurais pu passer le logo en svg :D

2018-02-16 08:39 UTC, merged

2018-02-16 10:43 UTC, hanfi commented
But not deployed 👎