add konami code feature
24chevres/24chevres.com pull request #25
Opened 2018-03-07 17:19 UTC by hanfi

2018-03-07 17:30 UTC, RidaBiki commented
la vérité c'est beau !

2018-03-07 17:31 UTC, izeau commented
👍 for the feature. 👎 for the implementation. Please provide a konami code snippet instead of requiring it from `node_modules`

2018-03-08 09:01 UTC, deuzu commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/konami@1.6.0/konami.min.js"></script>
checksum plz

2018-03-08 09:01 UTC, deuzu commented on index.html
> +    var easter_egg = new Konami(function() {
```javascript
new Konami(() => {
    const audio = new Audio('assets/audio/screaming_goat.mp3');
    audio.play();
};
```

2018-03-08 09:04 UTC, deuzu commented
Reverting :-1: to :+1: when checksum is ok
See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

2018-03-08 09:49 UTC, izeau requested changes

2018-03-08 09:49 UTC, izeau commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/konami@1.6.0/konami.min.js"></script>
Also reset `package-lock.json` changes.

2018-03-08 11:11 UTC, hanfi commented on index.html
> +    var easter_egg = new Konami(function() {
putin j'aime beaucoup comment tu écris ton js !!! toi t'es pas un charlatan

2018-03-08 11:13 UTC, deuzu commented
@hanfi Why is the package-lock.json has a diff if you're using a CDN?

2018-03-09 12:57 UTC, merged